---
- name: Run 'show vlan' on Cisco devices
  hosts: USWI_DC01_FL01_SWITCHES
  gather_facts: no
  collections:
    - cisco.ios  
  tasks:
    - name: Execute show vlan command
      ios_command:
        commands: show vlan
      register: vlan_output

    - name: Display VLAN command output
      debug:
        var: vlan_output.stdout_lines
